version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - vlombat-network  # Use the custom network

volumes:
  mongo-data:
    driver: local

networks:
  vlombat-network:  # Define the custom network
    external: true  # Indicates this network is managed outside of this compose file