###
GET http://localhost:3092

###
POST http://localhost:3092/fight
Content-Type: application/json

{
  "fighter1": {
    "name": "Биба",
    "powerMin": 3,
    "powerMax": 15
  },
  "fighter2": {
    "name": "Боба",
    "powerMin": 32,
    "powerMax": 153
  }
}

###
POST http://localhost:3092/chat
Content-Type: application/json

{
  "message": "do you play mortal kombat ultimate?"
}

###
POST http://localhost:3092/chat
Content-Type: application/json

{
  "message": "Идет драка между двумя людьми, их зовут Биба и Боба. Боба использует вяленую сельдь как оружие. Биба исользует токсический плевок как оружие. Каждый наносит повреждение противнику. Опиши смешно используя максимум 2 предложения"
}

###
POST http://localhost:3092/chat
Content-Type: application/json

{
  "message": "Опиши смешно используя 1 короткое предложение. Идет драка, человек по имени Биба атакует человека по имени Боба используя в качестве оружия вяленую сельдь. Боба получает серьезные повреждения"
}


###
POST http://localhost:3092/chat
Content-Type: application/json

{
  "message": "Игрок Биба использует оружие сушеная сельдь. Игрок Боба использует оружие токсичный плевок. Биба наносит урон Боба. Опиши как Боба наносит урон Биба. Опиши смешно используя максимум 2 предложения"
}

###
POST http://localhost:3092/chat
Content-Type: application/json

{
  "message": "we need to simulate a fight between to players in mortal kombat descriptive style. fight will last multiple rounds where each player hits with his damage one time. in each round we need a text description what actions was performed and how much damage each player dealt. First player name is Biba, health: 100, min damage: 3, max damage: 15. Second player name is Boba, health: 55, min damage: 13, max damage: 25. Fight ends when any of players health is below 0. Answer format must be json array of rounds with fields: p1RemainingHealth, p2RemainingHealth, text"
}

